# Generated by Django 5.1 on 2025-07-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bege", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_desc",
            field=models.TextField(),
        ),
    ]
